$background = 010303
$onBackground = dde7e8
$surface = 010303
$surfaceDim = 010303
$surfaceBright = 080e0f
$surfaceContainerLowest = 000000
$surfaceContainerLow = 020505
$surfaceContainer = 030708
$surfaceContainerHigh = 050a0a
$surfaceContainerHighest = 060c0c
$onSurface = dde7e8
$surfaceVariant = 060c0c
$onSurfaceVariant = a2adae
$outline = 6d7778
$outlineVariant = 3f4a4b
$inverseSurface = f6fafa
$inverseOnSurface = 515656
$shadow = 000000
$scrim = 000000
$surfaceTint = 182b2c
$primary = 9cd0d4
$primaryDim = 8ec2c7
$onPrimary = 0c474c
$primaryContainer = 255a5e
$onPrimaryContainer = b8edf2
$inversePrimary = 33676b
$primaryFixed = b7ecf1
$primaryFixedDim = a9dee3
$onPrimaryFixed = 0b464b
$onPrimaryFixedVariant = 2f6368
$secondary = b1cbce
$secondaryDim = a3bec0
$onSecondary = 2c4447
$secondaryContainer = 273f42
$onSecondaryContainer = aac4c7
$secondaryFixed = cce8ea
$secondaryFixedDim = bed9dc
$onSecondaryFixed = 2b4346
$onSecondaryFixedVariant = 476062
$tertiary = badeff
$tertiaryDim = abd0f1
$onTertiary = 2b506c
$tertiaryContainer = abd0f1
$onTertiaryContainer = 214762
$tertiaryFixed = abd0f1
$tertiaryFixedDim = 9ec2e3
$onTertiaryFixed = 06334e
$onTertiaryFixedVariant = 2b506c
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 4c7f84
$secondaryPaletteKeyColor = 627c7e
$tertiaryPaletteKeyColor = 577b99
$neutralPaletteKeyColor = 737878
$neutralVariantPaletteKeyColor = 6e797a
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 4c7f84
$secondary_paletteKeyColor = 627c7e
$tertiary_paletteKeyColor = 577b99
$neutral_paletteKeyColor = 737878
$neutral_variant_paletteKeyColor = 6e797a
$term0 = 080808
$term1 = 769e00
$term2 = 48e2d0
$term3 = 75fcdd
$term4 = 76b5ba
$term5 = 7aaee9
$term6 = 80d8d4
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = 85b900
$term10 = 22f7e3
$term11 = cafff1
$term12 = a3c8c8
$term13 = a2c0f7
$term14 = 87ece5
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 68ccf1
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d1faef
$green = 8af1ec
$teal = 9eedf1
$sky = 93e9f2
$sapphire = 72d6e5
$blue = 5ccbe4
$lavender = 8ad8f0
$klink = 0095a7
$klinkSelection = 0095a9
$kvisited = 008cb0
$kvisitedSelection = 008bb1
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb8
$kpositiveSelection = 00bcba
$text = dde7e8
$subtext1 = a2adae
$subtext0 = 6d7778
$overlay2 = 181918
$overlay1 = 151616
$overlay0 = 121313
$surface2 = 0d1010
$surface1 = 080b0b
$surface0 = 020505
$base = 000000
$mantle = 000000
$crust = 000000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
