foreground            #dce4e8
background            #0d1418
selection_foreground  #3d2f00
selection_background  #e6c361
url_color             #94cfe9
cursor                #e6c361
cursor_text_color     #3d2f00

color0   #0d1418
color1   #ffb4ab
color2   #e6c361
color3   #94cfe9
color4   #e6c361
color5   #94cfe9
color6   #004d63
color7   #dce4e8

color8   #84939a
color9   #ffb4ab
color10  #e6c361
color11  #94cfe9
color12  #e6c361
color13  #94cfe9
color14  #004d63
color15  #dce4e8

tab_bar_background              #0d1418
tab_bar_margin_color            #0d1418
active_tab_foreground           #3d2f00
active_tab_background           #e6c361
inactive_tab_foreground         #bac9d1
inactive_tab_background         #0d1418
