# https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

$CONFIGS = /home/akio/.config/hypr/configs

source = $CONFIGS/animations.conf
source = $CONFIGS/binds.conf
source = $CONFIGS/environ.conf
source = $CONFIGS/exec.conf
source = $CONFIGS/monitor.conf
source = $CONFIGS/rules.conf
source = $CONFIGS/setting.conf








