splash = false
wallpaper {
  monitor = eDP-1
  path = /home/akio/wallpaper/wallpaper6.png
  fit_mode = cover
}
wallpaper {
  monitor = null
  path = /home/akio/wallpaper/wallpaper6.png
  fit_mode = cover
}
