exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once =   sudo mount -t ntfs3 -o uid=$(id -u),gid=$(id -g),rw /dev/nvme0n1p3 /mnt/windows
exec-once = eww daemon && eww open bar_widget 2>/dev/null && sleep 1 && eww open calendar && eww open usrctl && eww open menuctl 2>/dev/null
#exec-once = waybar
#exec-once = hyprpaper
# exec-once = caelestia shell -d
exec-once = noctalia -d


exec-shutdown = ~/.config/hypr/scripts/clear_clipboard.sh
